export const timezones = [
  { value: "UTC", label: "UTC" },
  { value: "Africa/Cairo", label: "(GMT+2:00) Cairo" },
  { value: "Africa/Johannesburg", label: "(GMT+2:00) Johannesburg" },
  { value: "Africa/Lagos", label: "(GMT+1:00) Lagos" },
  { value: "Africa/Nairobi", label: "(GMT+3:00) Nairobi" },
  { value: "America/Chicago", label: "(GMT-6:00) Chicago" },
  { value: "America/Los_Angeles", label: "(GMT-8:00) Los Angeles" },
  { value: "America/Mexico_City", label: "(GMT-6:00) Mexico City" },
  { value: "America/New_York", label: "(GMT-5:00) New York" },
  { value: "America/Sao_Paulo", label: "(GMT-3:00) São Paulo" },
  { value: "Asia/Dubai", label: "(GMT+4:00) Dubai" },
  { value: "Asia/Hong_Kong", label: "(GMT+8:00) Hong Kong" },
  { value: "Asia/Jakarta", label: "(GMT+7:00) Jakarta" },
  { value: "Asia/Shanghai", label: "(GMT+8:00) Shanghai" },
  { value: "Asia/Singapore", label: "(GMT+8:00) Singapore" },
  { value: "Asia/Tokyo", label: "(GMT+9:00) Tokyo" },
  { value: "Australia/Melbourne", label: "(GMT+10:00) Melbourne" },
  { value: "Australia/Sydney", label: "(GMT+10:00) Sydney" },
  { value: "Europe/Amsterdam", label: "(GMT+1:00) Amsterdam" },
  { value: "Europe/Berlin", label: "(GMT+1:00) Berlin" },
  { value: "Europe/London", label: "(GMT+0:00) London" },
  { value: "Europe/Madrid", label: "(GMT+1:00) Madrid" },
  { value: "Europe/Moscow", label: "(GMT+3:00) Moscow" },
  { value: "Europe/Paris", label: "(GMT+1:00) Paris" },
  { value: "Europe/Rome", label: "(GMT+1:00) Rome" },
  { value: "Pacific/Auckland", label: "(GMT+12:00) Auckland" },
];
